from __future__ import annotations

import asyncio
import json
import threading
from collections.abc import Callable
from functools import partial
from typing import Any

from agentdna.mcp.context import get_context
from agentdna.mcp.metadata import (
    workflow_from_metadata,
    workflow_to_metadata,
)
from agentdna.types import RESULT_OK

_PATCH_INSTALLED = False
_PATCH_LOCK = threading.Lock()

_ORIGINAL_MCPADAPT_TOOLS: Callable[..., Any] | None = None
_ORIGINAL_CREWAI_ADAPTER_ADAPT: Callable[..., Any] | None = None


def install_mcp_client() -> None:
    """
    Install AgentDNA integration into CrewAI's MCPServerAdapter stack.

    CrewAI's MCPServerAdapter uses mcpadapt.MCPAdapt with
    crewai_tools.adapters.mcp_adapter.CrewAIToolAdapter.

    AgentDNA instruments each actual MCP tools/call request by:

        1. creating an AgentDNA request workflow
        2. propagating it through MCP _meta
        3. executing the real MCP request
        4. treating MCP errors as terminal AgentDNA failures
        5. extracting the AgentDNA successor on success
        6. advancing the causal frontier

    The patch is installed explicitly and is safe to call multiple times.
    """

    global _PATCH_INSTALLED
    global _ORIGINAL_MCPADAPT_TOOLS
    global _ORIGINAL_CREWAI_ADAPTER_ADAPT

    if _PATCH_INSTALLED:
        return

    with _PATCH_LOCK:
        if _PATCH_INSTALLED:
            return

        try:
            import mcpadapt.core
            from crewai_tools.adapters.mcp_adapter import CrewAIToolAdapter
        except ImportError as exc:
            raise ImportError(
                "CrewAI MCP support is not available. "
                "Install it with `pip install 'crewai-tools[mcp]'`."
            ) from exc

        original_tools = mcpadapt.core.MCPAdapt.tools
        original_adapt = CrewAIToolAdapter.adapt

        # ------------------------------------------------------------------
        # Patch CrewAI's actual MCP adapter.
        #
        # This is the adapter actually passed to MCPAdapt by
        # crewai_tools.MCPServerAdapter.
        # ------------------------------------------------------------------

        def agentdna_adapt(
            self: Any,
            func: Callable[..., Any],
            mcp_tool: Any,
        ) -> Any:
            tool = original_adapt(
                self,
                func,
                mcp_tool,
            )

            # The MCP tool generated by CrewAI is under our control.
            #
            # Setting this on the generated tool means developers do not
            # need to configure tool_failure_policy on their Agent.
            try:
                from crewai.tools.tool_failure import ToolFailurePolicy

                tool.tool_failure_policy = ToolFailurePolicy.RAISE
            except ImportError:
                # Supported CrewAI versions have this module.
                pass

            return tool

        # ------------------------------------------------------------------
        # Patch MCPAdapt.tools().
        #
        # mcpadapt 0.1.20 builds the synchronous MCP callable internally as:
        #
        #     session.call_tool(name, arguments)
        #
        # We replace only that callable while preserving the rest of
        # MCPAdapt's lifecycle and event-loop management.
        # ------------------------------------------------------------------

        def agentdna_tools(self: Any) -> list[Any]:
            if not self.sessions:
                raise RuntimeError("Session not initialized")

            def _sync_call_tool(
                session: Any,
                name: str,
                arguments: dict[str, Any] | None = None,
            ) -> Any:
                context = get_context()

                # ----------------------------------------------------------
                # No AgentDNA context.
                #
                # Completely preserve normal MCPAdapt behaviour.
                # ----------------------------------------------------------

                if context is None:
                    return asyncio.run_coroutine_threadsafe(
                        session.call_tool(
                            name,
                            arguments,
                        ),
                        self.loop,
                    ).result()

                async def _agentdna_call() -> Any:
                    call_handle = await context.begin_mcp_call()

                    completed = False
                    cancelled = False

                    try:
                        actual_arguments = arguments or {}

                        # --------------------------------------------------
                        # Build AgentDNA request workflow.
                        # --------------------------------------------------

                        request_payload = build_mcp_tool_call_payload(
                            name=name,
                            arguments=actual_arguments,
                        )

                        request_workflow = context.dna.build(
                            payload=request_payload,
                            previous_workflows=list(call_handle.batch.parent_frontier),
                            verification_code=RESULT_OK,
                        )

                        request_meta = workflow_to_metadata(request_workflow)

                        # --------------------------------------------------
                        # Actual MCP request.
                        # --------------------------------------------------

                        result = await session.call_tool(
                            name,
                            actual_arguments,
                            meta=request_meta,
                        )

                        # --------------------------------------------------
                        # MCP-level failure.
                        #
                        # FastMCP may serialize an exception raised by the
                        # middleware into CallToolResult(is_error=True).
                        #
                        # Never return this to CrewAI as ordinary tool
                        # output. Convert it into CrewAI's deliberate-stop
                        # exception instead.
                        # --------------------------------------------------

                        if _is_mcp_error_result(result):
                            error_message = _extract_result_text(result) or "MCP tool call failed"

                            await context.cancel_mcp_call(call_handle)
                            cancelled = True

                            _raise_crewai_terminal_failure(
                                tool_name=name,
                                tool_arguments=actual_arguments,
                                message=error_message,
                            )

                        # --------------------------------------------------
                        # Successful MCP request.
                        #
                        # AgentDNA requires a successor workflow.
                        # --------------------------------------------------

                        successor = workflow_from_metadata(
                            getattr(
                                result,
                                "meta",
                                None,
                            )
                        )

                        if successor is None:
                            await context.cancel_mcp_call(call_handle)
                            cancelled = True

                            raise RuntimeError(
                                "CrewAI MCP tool response did not contain "
                                "an AgentDNA successor workflow"
                            )

                        verification_code = context.dna.verify(successor)

                        if verification_code != RESULT_OK:
                            await context.cancel_mcp_call(call_handle)

                            failed_workflow = context.dna.build(
                                payload=f"CoCA: failed to verify signature for workflow received from the {successor.get_latest_envelope_actor()}",
                                previous_workflows=successor,
                                verification_code=verification_code,
                            )
                            context.dna.record(failed_workflow)

                            raise ValueError(
                                f"CoCA verification failed for workflow recieved from the {successor.get_latest_envelope_actor()}"
                            )

                        await context.complete_mcp_call(
                            call_handle,
                            successor,
                        )
                        completed = True

                        return result

                    except Exception:
                        if not completed and not cancelled:
                            await context.cancel_mcp_call(call_handle)

                        raise

                return asyncio.run_coroutine_threadsafe(
                    _agentdna_call(),
                    self.loop,
                ).result()

            # Temporarily replace the adapter's bound adapt method so that
            # only tools generated by this MCPAdapt instance get the
            # AgentDNA failure policy.
            original_bound_adapt = self.adapter.adapt

            try:
                self.adapter.adapt = partial(
                    agentdna_adapt,
                    self.adapter,
                )

                return [
                    self.adapter.adapt(
                        partial(
                            _sync_call_tool,
                            session,
                            tool.name,
                        ),
                        tool,
                    )
                    for session, tools in zip(self.sessions, self.mcp_tools, strict=False)
                    for tool in tools
                ]

            finally:
                self.adapter.adapt = original_bound_adapt

        _ORIGINAL_MCPADAPT_TOOLS = original_tools
        _ORIGINAL_CREWAI_ADAPTER_ADAPT = original_adapt

        # Install the two patches.
        CrewAIToolAdapter.adapt = agentdna_adapt
        mcpadapt.core.MCPAdapt.tools = agentdna_tools

        _PATCH_INSTALLED = True


def _is_mcp_error_result(
    result: Any,
) -> bool:
    """
    Return True when the MCP result represents a tool-level error.

    MCP Python SDK normally exposes this as `is_error`.
    """

    is_error = getattr(
        result,
        "is_error",
        None,
    )

    if is_error is None:
        is_error = getattr(
            result,
            "isError",
            False,
        )

    return bool(is_error)


def _extract_result_text(
    result: Any,
) -> str | None:
    """
    Extract human-readable text from an MCP result.
    """

    content = getattr(
        result,
        "content",
        None,
    )

    if not content:
        return None

    messages: list[str] = []

    for item in content:
        text = getattr(
            item,
            "text",
            None,
        )

        if (
            isinstance(
                text,
                str,
            )
            and text
        ):
            messages.append(text)

    if not messages:
        return None

    return " | ".join(messages)


def _raise_crewai_terminal_failure(
    tool_name: str,
    tool_arguments: dict[str, Any],
    message: str,
) -> None:
    """
    Raise CrewAI's deliberate-stop exception.

    CrewAI 1.15.x treats ToolExecutionFailedError as a passthrough
    exception rather than a normal retryable execution error.
    """

    from crewai.tools.tool_failure import (
        ToolExecutionFailedError,
        ToolFailure,
        ToolFailureReason,
        ToolFailureRecord,
    )

    failure = ToolFailure(
        message=message,
        reason=ToolFailureReason.MCP_ERROR,
        code="AGENTDNA_MCP_ERROR",
        retryable=False,
        details={
            "agentdna": True,
            "tool": tool_name,
            "arguments": tool_arguments,
        },
    )

    record = ToolFailureRecord(
        tool_name=tool_name,
        failure=failure,
        tool_args=tool_arguments,
    )

    raise ToolExecutionFailedError(record)


def build_mcp_tool_call_payload(
    name: str,
    arguments: dict[str, Any] | None,
) -> str:
    """
    Build the canonical AgentDNA representation of one MCP
    tools/call request.

    JSON-RPC transport framing is intentionally excluded.
    """

    return json.dumps(
        {
            "method": "tools/call",
            "params": {
                "name": name,
                "arguments": arguments,
            },
        },
        separators=(
            ",",
            ":",
        ),
        sort_keys=True,
    )
